### Pandas Manipulations Practice

In [27]:
# general
import numpy as np
import pandas as pd
pd.plotting.register_matplotlib_converters()

# mpl
import matplotlib as mpl
import matplotlib.pyplot as plt

# plotly
import plotly.express as px
import plotly.io as pio
import plotly.figure_factory as ff
pio.renderers.default = 'iframe'

# datetime
from datetime import datetime


# stats
from scipy import stats
from lmfit.models import GaussianModel

#### 1. Date difference

In [5]:
# get data
museum_path = '../data/datavis/museum_visitors.csv'
museum_data = pd.read_csv(museum_path)

In [7]:
museum_data.tail()

,Date,Avila Adobe,Firehouse Museum,Chinese American Museum,America Tropical Interpretive Center
54,2018-07-01,23136,4191,2620,4718
55,2018-08-01,20815,4866,2409,3891
56,2018-09-01,21020,4956,2146,3180
57,2018-10-01,19280,4622,2364,3775
58,2018-11-01,17163,4082,2385,4562

In [8]:
museum_data.dtypes

Date                                    object
Avila Adobe                              int64
Firehouse Museum                         int64
Chinese American Museum                  int64
America Tropical Interpretive Center     int64
dtype: object

In [10]:
# parse date
museum_data['Date'] = pd.to_datetime(museum_data.Date,format="%Y-%m-%d")
museum_data.dtypes

Date                                    datetime64[ns]
Avila Adobe                                      int64
Firehouse Museum                                 int64
Chinese American Museum                          int64
America Tropical Interpretive Center             int64
dtype: object

In [31]:
today = datetime.today()
today = pd.to_datetime('2019-01-01',format='%Y-%m-%d')

museum_data['days_elapsed'] = (today - museum_data.Date).dt.days

museum_data.sort_values('days_elapsed', inplace=True, ascending=False)
museum_data.head()

,Date,Avila Adobe,Firehouse Museum,Chinese American Museum,America Tropical Interpretive Center,days_elapsed
0,2014-01-01,24778,4486,1581,6602,1826
1,2014-02-01,18976,4172,1785,5029,1795
2,2014-03-01,25231,7082,3229,8129,1767
3,2014-04-01,26989,6756,2129,2824,1736
4,2014-05-01,36883,10858,3676,10694,1706

In [37]:
aa_atendance = museum_data['Avila Adobe'].groupby(museum_data.Date.dt.year).mean()

In [38]:
px.line(aa_atendance)